// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTYHq4Xr52hE-LWtisn__qVNYw-kg7gwM',
    appId: '1:100867415297:android:f7d6cfe4be3b37c4e98f00',
    messagingSenderId: '100867415297',
    projectId: 'panamera-4ae33',
    storageBucket: 'panamera-4ae33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs5qcRbOLAY9MlYamL9X8n8n7ATcZGJto',
    appId: '1:100867415297:ios:e93e30a0e182a0b1e98f00',
    messagingSenderId: '100867415297',
    projectId: 'panamera-4ae33',
    storageBucket: 'panamera-4ae33.firebasestorage.app',
    iosBundleId: 'com.panamera.app.panameraApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7EtTTmhwgSz_iJ_oySoGPvcM1KHs3rhQ',
    appId: '1:100867415297:web:d71c88ad439d31f4e98f00',
    messagingSenderId: '100867415297',
    projectId: 'panamera-4ae33',
    authDomain: 'panamera-4ae33.firebaseapp.com',
    storageBucket: 'panamera-4ae33.firebasestorage.app',
    measurementId: 'G-ZPM9KSR2LJ',
  );

}